# Generated by Django 5.1.2 on 2024-11-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='sin categoria', max_length=50),
        ),
    ]
