# Generated by Django 5.1.2 on 2024-11-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_producto_stock_compra_compraproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
