# Generated by Django 5.1.2 on 2024-11-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0009_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
